// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Channel struct {
	Name   string `json:"name"`
	Height int    `json:"height"`
	Config string `json:"config"`
}

type SyncChannelResponse struct {
	Success         bool     `json:"success"`
	ApplicationTxID string   `json:"applicationTxId"`
	OrdererTxID     string   `json:"ordererTxId"`
	OrderersJoined  []string `json:"orderersJoined"`
	PeersJoined     []string `json:"peersJoined"`
}
